version: '3'
services:
  nginx:
    depends_on:
      - server-app
      - client-app
    restart: always
    build: ./nginx
    ports:
      - "8114:80"
  server-app:
    build: ./serverApp
    ports:
      - "8112:3000"
  client-app:
    build: ./clientApp
    ports:
      - "8113:8100"
    volumes:
      - /app/node_modules
      - ./clientApp:/app